ProjectManagerAws/ProjectManagerAws/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls import include as confinclude

from projectMgr import views

from rest_framework import routers
from rest_framework.authtoken import views as restauthviews
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'projects',views.ProjectViewSet)
router.register(r'taskgroups', views.TaskGroupViewSet)
router.register(r'tasks',views.TaskViewSet)

urlpatterns = [

    # url('',include('allauth.urls')),

    # url(r'^accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',include('projectMgr.urls')),

    path('', include(router.urls)),
    # url('^activity/',include('actstream.urls')),

    #rest auth
    url(r'^rest-auth/',include('rest_auth.urls')),
    url(r'^rest-auth/registration/',include('rest_auth.registration.urls')),


    #rest-framework auth
    url('api-token-auth/',restauthviews.obtain_auth_token),

    path('api-auth/', confinclude('rest_framework.urls', namespace='rest_framework')),

]

ProjectManagerAws/projectMgr/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'projectMgr'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('signin/',views.signin,name='signin'),
    path('signup/',views.signUp,name='signup'),
    path('userhome/',views.userHome,name='userhome'),
    path('logout/',views.logoutReq,name='logout'),
    path('<int:projectid>/<int:taskGroupId>/createTask/', views.taskCreate, name='createTask'),
    path('<int:projectid>/chooseProjectMates/',views.chooseProjectMates2,name='chooseProjectMates'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/task/',views.taskDetail,name='taskDetail'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/<int:userid>/addToTask/', views.addToTask,name='addToTask'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/chooseTaskMates/',views.chooseTaskMates2,name='chooseTaskMates'),
    path('createProject/',views.projectCreate,name='projectCreate'),
    path('<int:projectid>/project/',views.projectDetail,name='projectDetail'),
    path('<int:projectid>/<int:userid>/addToProject',views.addToProject,name='addToProject'),
    path('<int:projectid>/projectDetailComment',views.projectDetailComment,name="projectDetailComment"),
    path('<int:projectid>/projectEdit/',views.projectDetailEdit,name='projectDetailEdit'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/taskEdit/',views.taskDetailEdit,name='taskDetailEdit'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/<int:userid>/taskMateRemove',views.taskMateRemove,name='taskMateRemove'),
    path('<int:projectid>/<int:userid>/removeProjectMates',views.projectMateRemove,name="projectMateRemove"),
    path('<int:projectid>/<int:taskGroupId>/removeTaskGroup', views.taskGroupRemove, name="taskGroupRemove"),
    path('<int:projectid>/<int:taskGroupId>/<int:userid>/taskGroupMateRemove',views.taskGroupMateRemove,name="taskGroupMateRemove"),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/taskRemove',views.taskRemove,name="taskRemove"),
    path('<int:projectid>/createTaskGroup/',views.taskGroupCreate,name='createTaskGroup'),
    path('<int:projectid>/<int:taskGroupId>/deleteTaskGroup/',views.taskDelete,name='taskDelete'),
    path('<int:projectid>/<int:taskGroupId>/chooseTaskGroupMates/',views.chooseTaskGroupMates2,name='chooseTaskGroupMates'),
    path('<int:projectid>/<int:taskGroupId>/<int:userid>/addToTaskGroup/', views.addToTaskGroup, name='addToTaskGroup'),
    path('<int:projectid>/<int:taskGroupId>/taskGroup/',views.taskGroupDetail,name='taskGroupDetail'),
    path('<int:projectid>/<int:taskGroupId>/taskGroupEdit/',views.taskGroupDetailEdit,name='taskGroupDetailEdit'),
    path('<int:projectid>/<int:taskGroupId>/taskGroupDetailComment',views.taskGroupDetailComment,name='taskGroupDetailComment'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/addComment',views.taskDetailComment,name='taskDetailComment'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/<int:commentid>/deleteComment',views.taskDeleteComment,name='taskDeleteComment'),
    path('<int:projectid>/<int:taskGroupId>/<int:commentid>/deleteComment',views.taskGroupDeleteComment,name="taskGroupDeleteComment"),
    path('<int:projectid>/<int:commentid>/deleteComment',views.projectDeleteComment,name='projectDeleteComment'),
    path('about/',views.about,name='about'),
    path('userinfo/',views.userinfo,name='userinfo'),
    path('upload_profile_pic/',views.uploadProfilePic,name='upload_profile_pic'),
    path('<int:projectid>/followProject',views.followProject, name='followProject'),
    path('<int:projectid>/<int:taskGroupId>/followTaskGroup', views.followTaskGroup, name='followTaskGroup'),
    path('<int:projectid>/<int:taskGroupId>/<int:taskid>/followTask', views.followTask, name='followTask'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectManagerAws/projectMgr/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

'''
1. there are multiple users.
2. people can create a project. this can be treated as a large project involving many people as part of the team.
3. the project has multiple task groups. 
4. each task group has multpile tasks at different stages.
5. each tasks have multiple people associated with it belonging to the project.

the projects can be archived for later access after use.
'''


# Create your models here.
class User(AbstractUser):
    profilePicture = models.CharField(max_length=200,null=True)
    fullName = models.CharField(max_length=100,null=True)
    bio = models.CharField(null=True,max_length=500)
    pass


class Comment(models.Model):
    '''
    created by
    created on
    modified on
    linkedto(if none, first comment, else, reply)

    '''
    createdOn = models.DateTimeField(auto_now=True)
    modifiedOn = models.DateTimeField()
    createdBy = models.ForeignKey(User, on_delete=models.CASCADE)
    textField = models.TextField()
    replyLink = models.ForeignKey('self', on_delete=models.CASCADE,null=True)
    deleted = models.BooleanField(default=False)

class Project(models.Model):
    '''
    need to have people associated with the project.
    one project can have many people and one person can be part of many projects. hence it could be a many to many relationship.

    the projects can have the option to be associated with teams. the team can be independant of the projects.
    everyone has the same permissions when it comes to creating the project. they cannot delete it for others.

    the project can have different tasks with different stages. i can have a one-one relationship to the datastructure which handles the event transitions.


    '''
    name = models.CharField(max_length=100)
    people = models.ManyToManyField(User,related_name="project_set")
    description = models.TextField()
    isArchived = models.BooleanField(default=False)
    comment = models.ManyToManyField(Comment)
    created = models.DateTimeField(auto_now=True)
    createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="projectIcreated",null=True)
    deadLine = models.DateTimeField(null=True)
    pass

class TaskGroup(models.Model):

    name = models.CharField(max_length=100)
    creator = models.ForeignKey(User,on_delete=models.CASCADE,related_name='taskgroupIcreated',null=True)
    description = models.TextField()
    project = models.ForeignKey(Project,on_delete=models.CASCADE,related_name="taskgroup_set",null=True)
    comment = models.ManyToManyField(Comment)
    people = models.ManyToManyField(User)
    created = models.DateTimeField(auto_now=True)
    DeadLine = models.DateTimeField(null=True)

class Task(models.Model):

    name = models.CharField(max_length=100)
    people = models.ManyToManyField(User)
    reporter = models.ForeignKey(User,related_name='Ireported',null=True,on_delete=models.PROTECT)
    description = models.TextField()
    taskGroup = models.ForeignKey(TaskGroup,on_delete=models.CASCADE,null=True)
    comment = models.ManyToManyField(Comment)
    created = models.DateTimeField(auto_now=True)
    stage = models.CharField(max_length=100) #initiate->in progress->review->done
    priority = models.CharField(max_length=100,default="Normal")
    deadLine = models.DateTimeField(null=True)
    pass

class taskFile(models.Model):
    name = models.CharField(max_length=100)
    task = models.ForeignKey(Task,on_delete=models.CASCADE)
    filePath = models.CharField(max_length=200)
    uploadedBy = models.ForeignKey(User,on_delete=models.PROTECT)
    uploadedOn = models.DateTimeField(auto_now=True)

ProjectManagerAws/projectMgr/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class signUp(UserCreationForm):
    email = forms.EmailField()
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','email','password1','password2']
    pass


class signIn(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100,widget=forms.PasswordInput)


class createProject(forms.Form):
    '''
    create Project
    name
    description
    people
    '''
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea, required=False)


    pass


class chooseMates2(forms.Form):
    search = forms.CharField(max_length=200, required=False)
    searchType = forms.ChoiceField(choices=[['username', 'username'], ['email', 'email']], required=False,
                                   widget=forms.RadioSelect, initial='email')



#depreciated
class chooseMates(forms.Form):
    '''
    have the user enter the emailid of the other users and press the search key.
    the search results should include the email id and the username. or we can have a selector whcih chooses
    between the two.
    '''

    search = forms.CharField(max_length=200,required=False)
    searchType = forms.ChoiceField(choices=[['username','username'],['email','email']],required=False,widget=forms.RadioSelect,initial='email')
    people = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,required=False)

    def __init__(self,  *args, peopleChoice=None, **kwargs):
        print("peopleChoice",peopleChoice)
        super().__init__(*args,**kwargs)
        if peopleChoice:
            # self.people.choices = peopleChoice
            self.fields['people'].choices = peopleChoice


class editTask(forms.Form):
    name = forms.CharField(max_length=100,required=True)
    description = forms.CharField(widget=forms.Textarea,empty_value="description default", required=False)
    stage = forms.ChoiceField(choices=[['OpenedIssue','OpenedIssue'],['InProgress','InProgress'],['InReview','InReview'],['ClosedIssue','ClosedIssue']])
    priority = forms.ChoiceField(choices=[["Urgent", "Urgent"], ['High', 'High'], ['Normal', 'Normal'], ['Low', 'Low']])
    def __init__(self,*args,nameVal=None,descriptionVal=None,stageVal=None,priority=None,**kwargs):
        super().__init__(*args,**kwargs)
        print("name is ",nameVal)
        if nameVal:
            self.fields['name'].initial = nameVal
        if descriptionVal:
            self.fields['description'].initial = descriptionVal
        if stageVal:
            self.fields['stage'].initial = stageVal
        if priority:
            self.fields['priority'].initial = priority


class editTaskGroup(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, empty_value="",required=False)

    def __init__(self, *args, nameVal=None, descriptionVal=None, **kwargs):
        super().__init__(*args, **kwargs)
        print("name is ", nameVal)
        if nameVal:
            self.fields['name'].initial = nameVal
        if descriptionVal:
            self.fields['description'].initial = descriptionVal


class editProject(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea, empty_value="", required=False)

    def __init__(self, *args, nameVal=None, descriptionVal=None, **kwargs):
        super().__init__(*args, **kwargs)
        print("name is ", nameVal)
        if nameVal:
            self.fields['name'].initial = nameVal
        if descriptionVal:
            self.fields['description'].initial = descriptionVal


class createTaskgroup(forms.Form):
    '''
    name
    description
    tasks:
    '''
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea,required=False)

    pass


class createTask(forms.Form):
    '''
    name
    description
    created
    modified
    deadline(optional)
    comments

    '''
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea, required=False)
    stage = forms.ChoiceField(choices=[['OpenedIssue', 'OpenedIssue'], ['InProgress', 'InProgress'], ['InReview', 'InReview'],
                 ['ClosedIssue', 'ClosedIssue']])
    priority = forms.ChoiceField(choices=[['Normal', 'Normal'], ["Urgent", "Urgent"], ['High', 'High'], ['low', 'low']])


class createComment(forms.Form):
    '''
    textField
    to handle whether a first comment or a reply in the models.
    '''
    Comment = forms.CharField(widget=forms.TextInput,max_length=500)
    pass


class uploadImage(forms.Form):
    '''
    title
    file
    '''
    title = forms.CharField(max_length=100)
    file = forms.FileField()

class uploadProfilePic(forms.Form):
    image = forms.FileField()

ProjectManagerAws/projectMgr/templates/projectMgr/taskDetailEdit.html
{% extends 'projectMgr/base.html' %}

{% block leftnav %}
<li><a href="{% url 'projectMgr:projectDetail' project.id %}" ><span class="glyphicon glyphicon-th-large"></span> {{project.name}}</a></li>
<li><a href="" ><span class="glyphicon glyphicon-menu-right"></span></a></li>
<li><a  href="{% url 'projectMgr:taskGroupDetail' project.id taskGroup.id %}" ><span class="glyphicon glyphicon-th"></span> {{taskGroup.name}}</a></li>
<li><a href="" ><span class="glyphicon glyphicon-menu-right"></span></a></li>
<li><a  href="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}" ><span class="glyphicon glyphicon-th-list"></span> {{ task.name }}</a></li>
<li class="active"><a href="{% url 'projectMgr:taskDetailEdit' project.id taskGroup.id task.id %}" ><span class="glyphicon glyphicon-cog"></span></a></li>

{% endblock %}


{% block body %}

    {% load crispy_forms_tags %}
    <form action="{% url 'projectMgr:taskDetailEdit' project.id taskGroup.id task.id %}" method="post">
    {% csrf_token %}


            {{ form|crispy}}


    <input type="submit" class="btn btn-primary" value="Done">
    </form>
<hr>
    <h5>Created:</h5>
    {% if thisUser == task.reporter %} Me {% else %} {{task.reporter.username }} {% endif %}

        , {{ task.created }}
{% endblock %}

{% block sidenav %}


      <a href="{% url 'projectMgr:chooseTaskMates' project.id taskGroup.id task.id %}" class="btn btn-primary">Task Team <span class="glyphicon glyphicon-plus"></span> </a>
   <hr>
            {% for person in taskGroup.people.all %}
             {% if person == thisUser %}
                <p><a style="margin: 3px"  href=""><span class="glyphicon glyphicon-user"></span> Me</a><a style="margin: 3px"  href="{% url 'projectMgr:taskMateRemove' project.id taskGroup.id task.id person.id %}"><span class="glyphicon glyphicon-minus-sign"></span></a></p>

                {% else %}
            <p><a style="margin: 3px"  href=""><span class="glyphicon glyphicon-user"></span> {{ person.username }}</a><a style="margin: 3px"  href="{% url 'projectMgr:taskMateRemove' project.id taskGroup.id task.id person.id %}"><span class="glyphicon glyphicon-minus-sign"></span></a></p>
            {% endif %}
        {% endfor %}
    <br>


{% endblock %}

ProjectManagerAws/projectMgr/templates/projectMgr/taskGroupDetail.html
{% extends 'projectMgr/base.html' %}

{% block leftnav %}
<li><a href="{% url 'projectMgr:projectDetail' project.id %}" ><span class="glyphicon glyphicon-th-large"></span> {{project.name}}</a></li>
<li><a href="" ><span class="glyphicon glyphicon-menu-right"></span></a></li>
<li class="active"><a  href="{% url 'projectMgr:taskGroupDetail' project.id taskGroup.id %}" ><span class="glyphicon glyphicon-th"></span> {{taskGroup.name}}</a></li>
<li><a href="{% url 'projectMgr:taskGroupDetailEdit' project.id taskGroup.id %}" ><span class="glyphicon glyphicon-cog"></span></a></li>

{% endblock %}

{% block heading %}
    <h4 style="display: inline-block"><span class="glyphicon glyphicon-th"></span> Task-Group</h4>
    <h3 style="display: inline-block;margin-right: 10px" > {{ taskGroup.name }} <h5 style="display: inline-block"><a href="{% url 'projectMgr:taskGroupDetailEdit' project.id taskGroup.id %}"> <i class="glyphicon glyphicon-pencil"></i></a> </h5></h3>
    <hr>
{% endblock %}

{% block body %}

        <h4 style="display: inline-block;margin-right: 10px" >Description <h5 style="display: inline-block"><a href="{% url 'projectMgr:taskGroupDetailEdit' project.id taskGroup.id %}"> <i class="glyphicon glyphicon-pencil"></i></a> </h5></h4>

    <p>
    {{ taskGroup.description }}
    </p>

        <hr>


<h4>Kanban Board:</h4>


    <div class="board">
    <div class="openedBoard">
    <h3>Opened Issues</h3>
    {% for task in OpenIssue %}
        {% if task.priority == "Urgent" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-danger" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "High" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-warning" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Normal" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-primary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Low" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-secondary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% endif %}
    {% endfor %}
    </div>
    <div class="inprogressBoard">
    <h3>In progress</h3>
    {% for task in InProgress %}
        {% if task.priority == "Urgent" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-danger" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "High" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-warning" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Normal" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-primary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Low" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-secondary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% endif %}
    {% endfor %}

    </div>
    <div class="inreviewBoard">
    <h3>In review</h3>
    {% for task in InReview %}
        {% if task.priority == "Urgent" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-danger" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "High" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-warning" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Normal" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-primary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Low" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-secondary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% endif %}
    {% endfor %}
    </div>
    <div class="closedBoard">
    <h3>Closed Issues</h3>
    {% for task in ClosedIssue %}
        {% if task.priority == "Urgent" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-danger" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "High" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-warning" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Normal" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-primary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% elif task.priority == "Low" %}

            <form action="{% url 'projectMgr:taskDetail' project.id taskGroup.id task.id %}">
        <input class="btn btn-secondary" style="width: 98%; margin: 1%; " type="submit" value={{ task.name }}>
        </form>

        {% endif %}
    {% endfor %}

    </div>
    </div>

    <p>Task priority:<div class="text-secondary" style="display: inline-block"><span class="glyphicon glyphicon-stop"></span></div> Low <div class="text-primary" style="display: inline-block"><span class="glyphicon glyphicon-stop"></span></div> Normal  <div class="text-warning" style="display: inline-block"><span class="glyphicon glyphicon-stop"></span></div> High  <div class="text-danger" style="display: inline-block"><span class="glyphicon glyphicon-stop"></span></div> Urgent </p>

<hr>
        {% load crispy_forms_tags %}
    <form action="{% url 'projectMgr:taskGroupDetailComment' project.id taskGroup.id%}" method="post">
    {% csrf_token %}

{{ commentForm|crispy }}
{#        {{ commentForm.text|as_crispy_field }}#}
    <input type="submit" class="btn btn-success" value="Post">

    </form>

    <hr>
     <p><span class="badge">{{nocomm }}</span> Comments <span class="glyphicon glyphicon-comment"></span></p><br>

    {% load static %}
    {% for comment in commentSet %}
    <div class="row">
        <div class="col-sm-2 text-center">
            <img src="{% static 'projectMgr/images/default_user.png' %}"  height="65" width="65" style=" border-radius: 5px" alt="">
        </div>
        <div class="col-sm-10">
            <h4>
                {% if comment.createdBy == thisUser %}
                Me
                {% else %}
                {{ comment.createdBy.username }}
                {% endif %}
                <small>{{comment.createdOn}}</small></h4>
            {% if comment.deleted %}
            <p style="color: gray">This comment was deleted</p>
            {% else %}
            <p>{{ comment.textField }}</p>
                {% if comment.createdBy == thisUser %}
                     <a href="{% url 'projectMgr:taskGroupDeleteComment' project.id taskGroup.id comment.id %}" ><span class="glyphicon glyphicon-minus-sign"></span></a>
                    {% endif %}
            {% endif %}

        </div>
        </div>
        <hr>

    {% endfor %}

{#    <hr>#}
    {% load activity_tags i18n %}
    <h4>Activity <a href="{% url 'projectMgr:followTaskGroup' project.id taskGroup.id%}">

        {% if thisUser|is_following:taskGroup %}
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
</svg>
    {% else %}
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z"/>
  <path fill-rule="evenodd" d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
</svg>
    {% endif %}
</a></h4>
{#    {% activity_stream 'actor' thisUser %}#}
    <table class="table">
  <thead class="thead-light">

  </thead>
  <tbody>

  {% for action in stream %}
      <tr>

   <td>{{ action.actor }} {{ action.verb }} <small style="color: #777777">{{ action.timestamp }}</small></td>

    </tr>

  {% endfor %}

  </tbody>
</table>


{% endblock %}


{% block sidenav %}
    <a href="{% url 'projectMgr:createTask' projectid=project.id taskGroupId=taskGroup.id %}" class="btn btn-primary">Task <span class="glyphicon glyphicon-plus"></span> </a>
   <hr>
            {% for task in taskGroup.task_set.all %}

                <p><a style="margin: 3px"  href="{% url 'projectMgr:taskDetail' projectid=project.id taskGroupId=taskGroup.id taskid=task.id %}"><span class="glyphicon glyphicon-th-list"></span> {{ task.name }}</a></p>

        {% endfor %}
    <br>

      <a href="{% url 'projectMgr:chooseTaskGroupMates' project.id taskGroup.id %}" class="btn btn-primary">Task Group Team <span class="glyphicon glyphicon-plus"></span> </a>
   <hr>
            {% for person in taskGroup.people.all %}
                {% if person == thisUser %}
                                <p><a style="margin: 3px"  href=""><span class="glyphicon glyphicon-user"></span> Me</a></p>

                {% else %}
            <p><a style="margin: 3px"  href=""><span class="glyphicon glyphicon-user"></span> {{ person.username }}</a></p>
                {% endif %}
        {% endfor %}
    <br>

{% endblock %}